import type { AttributeIconName } from '@agenda/core';
import {
  AppleLogoIcon,
  ArrowLeftIcon,
  BabyIcon,
  BeerSteinIcon,
  BellIcon,
  BellSimpleIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CaretDownIcon,
  CaretRightIcon,
  CarIcon,
  ChartBarIcon,
  ChatCircleIcon,
  CheckIcon,
  CheersIcon,
  ClockAfternoonIcon,
  ClockIcon,
  ConfettiIcon,
  CookingPotIcon,
  CreditCardIcon,
  DiscIcon,
  DogIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  FilePdfIcon,
  FloppyDiskIcon,
  ForkKnifeIcon,
  GearIcon,
  GlobeIcon,
  GoogleLogoIcon,
  HamburgerIcon,
  HeartIcon,
  HouseIcon,
  type Icon as PhosphorIcon,
  type IconWeight,
  ImageIcon,
  InfoIcon,
  InstagramLogoIcon,
  LaptopIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MartiniIcon,
  MegaphoneIcon,
  MicrophoneStageIcon,
  MountainsIcon,
  MusicNotesIcon,
  NavigationArrowIcon,
  PencilSimpleIcon,
  PlantIcon,
  PlusIcon,
  RainbowCloudIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  SoccerBallIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SquaresFourIcon,
  StarIcon,
  StorefrontIcon,
  TelevisionIcon,
  TicketIcon,
  TrashIcon,
  TreeIcon,
  TrophyIcon,
  UploadSimpleIcon,
  UserIcon,
  UsersIcon,
  WarningIcon,
  WhatsappLogoIcon,
  WheelchairIcon,
  WifiHighIcon,
  WindIcon,
  WineIcon,
  XIcon,
} from 'phosphor-react-native';

export type IconVariant = 'solid' | 'regular' | 'brands';

const WEIGHT_BY_VARIANT: Record<IconVariant, IconWeight> = {
  solid: 'fill',
  regular: 'regular',
  brands: 'fill',
};

export const DEFAULT_ICON_WEIGHT: IconWeight = 'regular';

const ICON_MAP = {
  apple: AppleLogoIcon,
  'arrow-left': ArrowLeftIcon,
  bell: BellIcon,
  'bell-simple': BellSimpleIcon,
  calendar: CalendarBlankIcon,
  'calendar-blank': CalendarBlankIcon,
  'calendar-check': CalendarCheckIcon,
  'caret-down': CaretDownIcon,
  check: CheckIcon,
  'chevron-right': CaretRightIcon,
  'chart-bar': ChartBarIcon,
  'circle-info': InfoIcon,
  clock: ClockIcon,
  comment: ChatCircleIcon,
  download: DownloadSimpleIcon,
  envelope: EnvelopeIcon,
  'envelope-simple': EnvelopeSimpleIcon,
  eye: EyeIcon,
  'file-pdf': FilePdfIcon,
  floppy: FloppyDiskIcon,
  gear: GearIcon,
  google: GoogleLogoIcon,
  heart: HeartIcon,
  house: HouseIcon,
  image: ImageIcon,
  instagram: InstagramLogoIcon,
  'location-arrow': NavigationArrowIcon,
  'location-dot': MapPinIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  microphone: MicrophoneStageIcon,
  music: MusicNotesIcon,
  pencil: PencilSimpleIcon,
  plus: PlusIcon,
  'right-from-bracket': SignOutIcon,
  'share-nodes': ShareNetworkIcon,
  'shield-check': ShieldCheckIcon,
  'shield-warning': ShieldWarningIcon,
  sliders: SlidersHorizontalIcon,
  'squares-four': SquaresFourIcon,
  star: StarIcon,
  store: StorefrontIcon,
  ticket: TicketIcon,
  'trash-can': TrashIcon,
  upload: UploadSimpleIcon,
  user: UserIcon,
  warning: WarningIcon,
  'wand-magic-sparkles': SparkleIcon,
  xmark: XIcon,
  accessible: WheelchairIcon,
  'air-conditioning': WindIcon,
  'audio-on': SpeakerHighIcon,
  beer: BeerSteinIcon,
  cheering: MegaphoneIcon,
  cocktail: MartiniIcon,
  counter: StorefrontIcon,
  date: WineIcon,
  deals: CheersIcon,
  dj: DiscIcon,
  family: UsersIcon,
  'free-entry': TicketIcon,
  'gluten-free': CookingPotIcon,
  globe: GlobeIcon,
  groups: UsersIcon,
  'happy-hour': ClockAfternoonIcon,
  kids: BabyIcon,
  'kids-menu': HamburgerIcon,
  laptop: LaptopIcon,
  lgbtq: RainbowCloudIcon,
  'meal-voucher': CreditCardIcon,
  'other-sports': TrophyIcon,
  outdoor: TreeIcon,
  parking: CarIcon,
  party: ConfettiIcon,
  pet: DogIcon,
  reservation: CalendarCheckIcon,
  romantic: WineIcon,
  'scenic-view': MountainsIcon,
  sports: SoccerBallIcon,
  trophy: TrophyIcon,
  tv: TelevisionIcon,
  vegan: PlantIcon,
  vegetarian: ForkKnifeIcon,
  whatsapp: WhatsappLogoIcon,
  wifi: WifiHighIcon,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICON_MAP;

const UNMAPPED_ATTRIBUTE_ICONS: never[] = [] as Exclude<AttributeIconName, IconName>[];
void UNMAPPED_ATTRIBUTE_ICONS;

export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];

export function resolveIcon(name: IconName): PhosphorIcon {
  return ICON_MAP[name];
}

export function resolveWeight(variant?: IconVariant): IconWeight {
  return variant ? WEIGHT_BY_VARIANT[variant] : DEFAULT_ICON_WEIGHT;
}

export function isIconName(value: string): value is IconName {
  return value in ICON_MAP;
}
